name: Cypress Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
    matrix:
      type: [e2e, component]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  

    - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
        node-version: 23.3.0

    - name: Install Dependencies
      run: npm ci                     

    - name: Run  Tests
      uses: cypress-io/github-action@v6  
      with:
        browser: chrome                   
        config-file: cypress.config.ts    
        spec: cypress/${{ matrix.type }}/**/*.cy.{js,jsx,ts,tsx}                      
